language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script: mvn install -DskipTest -q
install: /bin/true 
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
